name: setup java test

on:
  push:
    branches: [ "main" ]

  # Run on manual action
  workflow_dispatch:

jobs:
  test-setup-java:
    runs-on: [ ubuntu-latest ]
    container:
      image: ubuntu:22.04
    steps:
       - name: Checkout Repo
         uses: actions/checkout@v2
       - name: Setup Java
         uses: actions/setup-java@v3.11.0
         with:
           distribution: 'microsoft'
           java-version: '17.3'
